export const copy = {
  brand: "ETUDE",
  brandFa: "اتود",
  tagline: "پنل هنرجویی آموزشگاه موسیقی",
  login: {
    title: "ورود به پنل هنرجویی",
    subtitle: "نام و نام خانوادگی فارسی خود را وارد کنید",
    firstName: "نام",
    lastName: "نام خانوادگی",
    password: "رمز عبور",
    submit: "ورود به پنل",
    submitting: "در حال ورود…",
    demoHint: "پس از ثبت‌نام، به دوره استاد دهقانیار دسترسی دارید",
    error: "نام فارسی یا رمز عبور نادرست است",
    noAccount: "حساب ندارید؟",
    goRegister: "ثبت‌نام کنید",
  },
  register: {
    title: "ثبت‌نام هنرجو",
    subtitle: "برای دسترسی به دوره‌های آموزشگاه اتود حساب بسازید",
    firstName: "نام",
    lastName: "نام خانوادگی",
    password: "رمز عبور",
    confirmPassword: "تکرار رمز عبور",
    submit: "ایجاد حساب",
    submitting: "در حال ثبت‌نام…",
    hasAccount: "قبلاً ثبت‌نام کرده‌اید؟",
    goLogin: "وارد شوید",
    error: "ثبت‌نام انجام نشد. دوباره تلاش کنید.",
  },
  nav: {
    dashboard: "پیشخوان",
    courses: "دوره‌ها",
    sessions: "جلسات",
    schedule: "برنامه کلاس",
    profile: "پروفایل",
    logout: "خروج",
  },
  dashboard: {
    welcome: "خوش آمدید",
    nextLesson: "جلسه بعدی",
    myCourses: "دوره‌های من",
    weekSchedule: "برنامه هفته",
    practice: "تمرین پیشنهادی",
    seeAll: "مشاهده همه",
  },
} as const;
