export const copy = {
  brand: "ETUDE",
  brandFull: "ETUDE ACADEMY",
  brandSlogan: "Excellence in Life",
  brandFa: "اتود",
  academyName: "آکادمی تخصصی پیانو اتود",
  tagline: "پنل هنرجویی آکادمی تخصصی پیانو اتود",
  brandBlurb:
    "در این پنل هنرجویان و علاقه‌مندان به موسیقی می‌توانند به دوره‌های آموزشی، اسلایدهای مسترکلاس، فیلم‌های آموزشی و نت‌های پیانو دسترسی پیدا کنند.",
  passwordHint: "حداقل ۸ کاراکتر، شامل حروف و اعداد",
  copyright:
    "© ۱۴۰۵ ETUDE ACADEMY — تمامی حقوق برای آکادمی تخصصی پیانو اتود محفوظ است.",
  login: {
    title: "ورود به پنل هنرجویی",
    subtitle: "نام و نام خانوادگی فارسی خود را وارد کنید",
    firstName: "نام",
    lastName: "نام خانوادگی",
    password: "رمز عبور",
    submit: "ورود به پنل",
    submitting: "در حال ورود…",
    demoHint: "پس از ثبت‌نام، به دوره‌های آکادمی اتود دسترسی دارید",
    error: "نام فارسی یا رمز عبور نادرست است",
    noAccount: "حساب ندارید؟",
    goRegister: "ثبت‌نام کنید",
  },
  register: {
    title: "ثبت‌نام هنرجو",
    subtitle: "برای دسترسی به دوره‌های آکادمی اتود حساب بسازید",
    firstName: "نام",
    lastName: "نام خانوادگی",
    password: "رمز عبور",
    confirmPassword: "تکرار رمز عبور",
    submit: "ایجاد حساب",
    submitting: "در حال ثبت‌نام…",
    hasAccount: "قبلاً ثبت‌نام کرده‌اید؟",
    goLogin: "وارد شوید",
    error: "ثبت‌نام انجام نشد. دوباره تلاش کنید.",
  },
  nav: {
    dashboard: "پیشخوان",
    courses: "دوره‌ها",
    sessions: "جلسات",
    certificates: "مدارک",
    schedule: "برنامه کلاس",
    profile: "پروفایل",
    logout: "خروج",
  },
  dashboard: {
    welcome: "خوش آمدید",
    nextLesson: "جلسه بعدی",
    myCourses: "دوره‌های من",
    weekSchedule: "برنامه هفته",
    practice: "تمرین پیشنهادی",
    seeAll: "مشاهده همه",
  },
} as const;
