-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordPlain" VARCHAR(128);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" VARCHAR(32);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nationalId" VARCHAR(16);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "address" VARCHAR(500);
