export const copy = {
  brand: "ETUDE",
  brandFa: "اتود",
  tagline: "مسترکلاس تئوری موسیقی",
  login: {
    title: "ورود به پنل مسترکلاس",
    subtitle: "نام و نام خانوادگی فارسی خود را وارد کنید",
    firstName: "نام",
    lastName: "نام خانوادگی",
    password: "رمز عبور",
    submit: "ورود به پنل",
    submitting: "در حال ورود…",
    demoHint: "رمز مشترک دوره: etudepiano123",
    error: "نام فارسی یا رمز عبور نادرست است",
  },
  nav: {
    dashboard: "پیشخوان",
    courses: "جلسات",
    schedule: "برنامه کلاس",
    profile: "پروفایل",
    logout: "خروج",
  },
  dashboard: {
    welcome: "خوش آمدید به مسترکلاس",
    nextLesson: "جلسه بعدی",
    myCourses: "دورهٔ شما",
    weekSchedule: "برنامه هفته",
    practice: "تمرین پیشنهادی",
    seeAll: "مشاهده همه",
  },
} as const;
